version: '3'

services:
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
    - monitoring
      
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    networks:
    - deployml_network
    - monitoring
    ports:
      - "9090:9090"
    depends_on:
      - apiserver
      - modelserver
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    networks:
    - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./config/monitoring/grafana/dashboards:/etc/grafana/dashboards
  
networks:
  monitoring: