version: '3'

services:
  redis:
    image: redis
    networks:
    - deployml_network

  modelserver:
    build:
      context: .
      dockerfile: ./deploy/modelserver/Dockerfile
    container_name: modelserver
    restart: on-failure
    depends_on:
    - redis
    networks:
    - deployml_network
    env_file:
    - ./config/env/common.env
    - ./config/env/dev.env

  apiserver:
    build:
      context: .
      dockerfile: ./deploy/apiserver/Dockerfile
      target: dev
    container_name: apiserver
    restart: always
    ports:
    - "80:80"
    networks:
    - deployml_network
    depends_on:
    - redis
    - modelserver
    env_file:
    - ./config/env/common.env
    entrypoint: /start-reload.sh    # runs fastapi with live reloading when files are changed
    volumes:
      - ./apiserver:/app

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    networks:
    - deployml_network
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      
  grafana:
    image: grafana/grafana:8.4.5
    container_name: grafana
    networks:
    - deployml_network
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
        interval: 10s
        timeout: 10s
        retries: 5
  
  grafana-dashboards:
    container_name: grafana-dashboards
    image: alpine:3.14
    depends_on:
      - grafana
      - prometheus
    networks:
    - deployml_network
    restart: on-failure
    volumes:
      - ./config/monitoring:/grafana
    command: |
      /bin/sh -c "
      apk add \
        --no-cache \
        --allow-untrusted \
        --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/main \
        alpine-sdk  
      cd /grafana
      curl --request POST http://grafana:3000/api/datasources --header 'Content-Type: application/json' -d @datasources.json
      # curl --request POST http://grafana:3000/api/dashboards/db --header 'Content-Type: application/json' -d @dashboard.json
      "

volumes:
  mlflow-artifacts:

networks:
  deployml_network:
