global:
  scrape_interval:      15s
  evaluation_interval:  15s
scrape_configs:
- job_name: my-application
  honor_labels: true
  metrics_path: '/metrics'
  static_configs:
  - targets: ['apiserver:80']